### ISSUE TITLE
Can't get it to work on macOS

### ISSUE THREAD

**Issue by michaelbaisch** [dhelonious/PipenvPath#1]
I installed PipenvPath with the Sublime's Package Control.
I set the Build System simply to "Python" and in the preferences I also specifically set where the pipenv executable is:

```yaml
"pipenv_path":
  {
      "osx": "/opt/homebrew/bin/pipenv",
  },
```

But the virtualenv of pipenv isn't used. Looking in the source I see a few `print` commands. Should those be printed in the Sublime Console? I don't see any of them. Anything I can do to further debug this or did I do something completely wrong?
